### ISSUE TITLE
Improve how prediction intervals are estimated in forecasters using the direct strategy

### ISSUE THREAD

**Issue by JoaquinAmatRodrigo** [skforecast/skforecast#817]
### Discussed in https://github.com/JoaquinAmatRodrigo/skforecast/discussions/815

<div type='discussions-op-text'>

<sup>Originally posted by **MarcosBelver** October  8, 2024</sup>
I saw in the documentation that the n_boot parameter of the predict_interval function in the DirectForecaster is set to 500 by default.

I was wondering what is the mathematical/statistical explanation for this default selection. For example, if my set of residuals is ~150 (the training size is equal to that length) , does it make sense to oversampling the residuals obtaining a collection of 500 in order to get the corresponding quantile from there? Or this size of 500 is more oriented for longer training sets where the number of residuals is much bigger?

In that case, how to select the proper n_boot parameter for smaller residuals sample?

Thank you in advance.</div>

**Comment by MarcosBelver** [comment]
Hi guys, @JoaquinAmatRodrigo  @JavierEscobarOrtiz 

I take advantage of this post I opened a while ago. Doing some tests with small problems (less than 90) points I have observed that based on your implementation there could be a risk: the model is underestimating.

In that case, most of the residuals > 0. When you generate your bootstrapping intervals, in the way is coded, you will run the risk of having low intervals that could become 'higher' than your mean prediction.

I do not if its a confusion from my side, but I got to this conclusion analyzing the code. Anyway, i think that the possibilities are small (more prone in small problems) but I think they are still there...

Am i right on this?

**Comment by JoaquinAmatRodrigo** [comment]
Hi @MarcosBelver,
Thanks for providing more insight into how we use the residuals.
I think the behaviour you mention could happen if the residual distribution is very skewed towards positive values (the model is underestimating).

Do you have a reproducible example we could use to investigate further?

**Comment by MarcosBelver** [comment]
> Hi @MarcosBelver, Thanks for providing more insight into how we use the residuals. I think the behaviour you mention could happen if the residual distribution is very skewed towards positive values (the model is underestimating).
> 
> Do you have a reproducible example we could use to investigate further?

Sorry for late reply, Joaquin.

I cannot share the dataset since it contains private and sensible data, sorry. Anyway, after analyzing in more detail the residuals you were right: this is because the residuals are mostly positive values. This is something that could happen in some cases, specially (like in my case) when the time series length is quite short (~80 points) and suffer from high volatility.


On the other hand, some while ago I think I read you were planning to introduce conformal prediction. I do not if you have any advance on this topic, since I think it is a more robust method to provide CI (due to the limitation of this bootstrapping technique). Some while ago I was taking a look at the CP implementation of Nixtla library. Even though it is quite simple to understand the approach (it is as simple as generating the list of residuals from a CV partition), I am not fully convince where the term 'Conformal Prediction' is introduced, since from my understanding that requires to do some modifications to ensure you accomplish with the confidence intervals (but I think this is a question more suitable to ask to them).

Thank you advance for your time and response.

**Comment by JoaquinAmatRodrigo** [comment]
Hi, we are still in the research phase for the conformal approach. It does not seem to be as well defined for multi-step forecasting as it is for single-step forecasting. We may introuce the first conformal options in the next release.
I will close this topic and we can reopen it if there is any new information. Thanks for your feedback @MarcosBelver!
