### ISSUE TITLE
Allow `lags=None` and `window_features=None` if `use_exog_only=True`

### ISSUE THREAD

**Issue by lukashaenjes** [skforecast/skforecast#859]
Hi there, thanks for this excellent library!

I'm currently testing it for a daily store sales forecast, with stores open Mon-Sat and closed on Sun. I'm experimenting with different business logics on how to handle the closed Sundays and its impact on lags, e.g. should the lag_1 for Monday be NA because the store was closed on Sunday, or should it be the value of Saturday because the lag_1 refers to the "last open day" rather than the "last calendar day".

To fully evaluate this, I need more fine-grained control on how lags and the corresponding rolling window features are created. I currently create those in an independent preprocessing function and would like to pass them as "exogenous features" while setting `lags=None` and `window_features=None` in the instantiation of the `ForecasterRecursiveMultiSeries` class. 

However, this currently fails because of this check: https://github.com/skforecast/skforecast/blob/d7da9040268386795f9adb4ca5bd81b6d939697e/skforecast/recursive/_forecaster_recursive_multiseries.py#L371-L376

The issue is that the `exog=exog_dict_train` is only passed in the `.fit()`, *after* the forecaster is instantiated, so at the time of instantiation there is no way of knowing that lags and window features are going to be passed as exogenous feautures. So this check makes sense of course, but I would like to add a bit more control for use cases like mine. 

I propose adding a parameter such as `use_exog_only` to the `ForecasterRecursiveMultiSeries` and adjusting the check above as follows:

```python
if self.window_features is None and self.lags is None and self.use_exog_only is False:
    ...
```

We can keep it `False` by default to ensure backward compatability.

Happy to open a PR. What do you think?

**Comment by JavierEscobarOrtiz** [comment]
Hello @lukashaenjes 

Thanks for using skforecast.

You are right, the actual implementation requires at least one autoregressive feature (lag or window features) for Forecasters to work. However, in order to allow the behavior you mention, many additional modifications will be required despite removing this check.

If we understand your use case correctly, here are some suggestions:

- Exogenous features should not contain information from the target series. This is because their future values should be known at the time of the forecast.
- If the main concern is that Monday uses Saturday's values instead of Sunday's, you can preprocess the series to replace all Sunday values with Saturday's. 
- If you use a tree-based model and pass an exogenous variable with "day_of_week", it is likely that your model will learn this behavior (if `day_of_week = 'monday'`, the most important lag is the number 2).

We also recommend using a custom metric during backtesting to avoid including Sunday predictions as they are not of interest.

https://skforecast.org/latest/user_guides/backtesting#backtesting-with-custom-metric

Let us know if any of this helps in your use case.

Best,

Javi

**Comment by lukashaenjes** [comment]
Hi Javi, thanks for your feedback and the directions on how to accomodate my use case. Technically, a lag 7 is indeed known at the time of the forecast if I only forecast up to 7 days ahead, but I understand that many more modifications would be necessary to allow both `lags=None` and `window_features=None`. I will definitely check out the custom metrics.

Feel free to close this issue. Cheers!
